### Load in NumPy

In [1]:
import numpy as np

### The Basics

In [148]:
a = np.array([1,2,3], dtype='int16') # int32 is default
print(a)

[1 2 3]


In [149]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [150]:
# Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [151]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [152]:
# Get type
a.dtype

dtype('int16')

In [153]:
# Get size
print(a.itemsize)
print(b.itemsize)

2
8


In [154]:
# Get total size
print(a.size * a.itemsize)
print(a.nbytes)

6
6


### Accessing and Changing Elements, Rows, Columns

In [155]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [156]:
# Get a specific element [r, c]
print(a[1, 5])
print(a[1, -2])

13
13


In [157]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [38]:
# Getting a little more fancy [startindex:endindex+1:stepsize]
print(a[0, 1:6:2])
print(a[0, 1:-1:2])

[2 4 6]
[2 4 6]


In [39]:
# Change element
a[1,5] = 20
print(a)

a[:, 2] = 5
print(a)

a[:, 2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3D Example

In [40]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
# Get specific element (work outside in)
print(b[0,1,1])
print(b[:,1,:])

4
[[3 4]
 [7 8]]


In [45]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

b[:,1,:] = [[9,9,9],[8,8]] # Subsequence must be same dimension
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### Initializing Different Types of Arrays

In [49]:
# All 0a matrix
print(np.zeros(5))
print(np.zeros((2, 3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [50]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [52]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [55]:
# Any other number (full_like)
np.full(a.shape, 4)
np.full_like(a, 4) # Equivalent

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [57]:
# Random decimal numbers
print(np.random.rand(4,2))
print(np.random.random_sample(a.shape))

[[0.01918905 0.05141381]
 [0.05207589 0.77013738]
 [0.06821899 0.09723216]
 [0.40149414 0.34576919]]
[[0.94383773 0.57150767 0.761286   0.58849125 0.59325486 0.45826158
  0.46460523]
 [0.62101182 0.67966503 0.46677434 0.12619569 0.04490328 0.98721354
  0.9008529 ]]


In [86]:
# Random integer values
print(np.random.randint(7)) # Default start is 0, default shape is ()
print(np.random.randint(-4,8, size=(3,3))) # End value is exclusive

2
[[ 0 -3 -4]
 [ 2  2  6]
 [ 4 -3  3]]


In [87]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [90]:
# Repeat an array
arr = np.array([1,2,3]) # 1D array or vector
r1 = np.repeat(arr,3)
print(r1)

arr = np.array([[1,2,3]]) # 2D array
r1 = np.repeat(arr,3, axis=0)
r2 = np.repeat(arr,3, axis=1)
print(r1)
print(r2)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [91]:
# Array initialization practice
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z # Replace middle part of 1s matrix
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays!!!

In [96]:
# Incorrect - b and a point to the same array
a = np.array([1,2,3])
b = a
b[0] = 100
print(a) # Changing b also changes a

# Correct - b is a copy of a
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a) # Changing b does not change a

[100   2   3]
[1 2 3]


### Mathematics

In [104]:
# Arithmetic
a = np.array([1,2,3,4])
print(a)
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)
print()

a += 2 
print(a)
print()

b = np.array([1,0,1,0])
print(a + b)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]

[3 4 5 6]

[4 4 6 6]


In [106]:
# Trig functions
print(np.sin(a))
print(np.cos(a))

[ 0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[-0.9899925  -0.65364362  0.28366219  0.96017029]


In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [107]:
# Multiply matrices (recall 1st cols = 2nd rows, or else error)
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) # a*b will produce an error because different sizes

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [108]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [111]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)
print(np.min(stats))
print(np.max(stats, axis=1)) # Gives max of each row
print(np.sum(stats, axis=0)) # Gives sum of each column

[[1 2 3]
 [4 5 6]]
1
[3 6]
[5 7 9]


### Reorganizing Arrays

In [114]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2)) # Shape must have same # elements as original
print(after)

after = before.reshape((2,3)) # Error due to shape mismatch

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [115]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8]) # These two must be the same size

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [116]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

Load Data from File

In [118]:
filedata = np.genfromtxt('data.txt', delimiter=',') # Auto-casts to float
filedata = filedata.astype('int32') # Copies data into int32
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Boolean Masking and Advanced Indexing

In [132]:
# Find data that is > 50
print(filedata > 50)
print()

# Only grab values > 50
print(filedata[filedata > 50])
# This works because you can index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,2,8]]) # Also works with True/False
print()

# Find columns that have ANY values > 50
print(np.any(filedata > 50, axis=0))
print()

# Find columns that have ALL values > 50
print(np.all(filedata > 50, axis=0))
print()

# Find data that is NOT between 50 and 100 (~ means not)
print(~((filedata > 50) & (filedata < 100)))

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]

[196  75 766  75  55 999  78  76  88]
[2 3 9]

[False False False False  True  True False  True  True False False False
 False False False False  True  True]

[False False False False  True False False False False False False False
 False False False False False False]

[[ True  True  True  True  True False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True  True  True
   True  True  True  True False False]]


Indexing Practice

In [146]:
a = np.arange(1, 31).reshape(6,5)
print(a)
print(a[2:4,:2])
print(a[[0,1,2,3],[1,2,3,4]])
print(a[[0,4,5],3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
